# environment
env_name: cheetah/run
domain_name: null
task_name: null
pre_transform_image_size: 100
image_size: 84
action_repeat: 4
frame_stack: 3
# replay buffer
replay_buffer_capacity: 100000
# train
agent: ???
init_steps: 1000
num_env_steps: 105000 # 500100
batch_size: 512
hidden_dim: 1024
# eval
eval_freq: 5000
num_eval_episodes: 10
# critic
critic_lr: 2e-4
critic_beta: 0.9
critic_tau: 0.01
critic_target_update_freq: 2
# actor
actor_lr: 2e-4
actor_beta: 0.9
actor_log_std_min: -10
actor_log_std_max: 2
actor_update_freq: 2
# encoder
encoder_type: pixel
encoder_feature_dim: 50
encoder_lr: 2e-4
encoder_tau: 0.05
num_layers: 4
num_filters: 64
curl_latent_dim: 128
# sac
discount: 0.99
init_temperature: 0.1
alpha_lr: 1e-4
alpha_beta: 0.5
# cycdm
augmentation: ["crop", "intensity"]
jumps: 6
transition_model_type: 'deterministic'
transition_model_layer_width: 512
latent_dim: 100
auxiliary_task_batch_size: 128
time_offset: 0
momentum_tau: 0.05
aug_prob: 1.0
num_aug_actions: 10
loss_space: y
bp_mode: gt
cycle_steps: 6
cycle_mode: fp+cycle  # fp # fp+cycle # fp+bp+cycle
fp_loss_weight: 1.0
bp_loss_weight: 1.0
rc_loss_weight: 0.0
vc_loss_weight: 1.0
reward_loss_weight: 0.0
auxiliary_task_lr: 2e-4
sigma: 0.1
warmup: false
# misc
seed: null
gpuid: null
seed_and_gpuid: [-1, 0]
work_dir: ???
save_tb: true
save_buffer: false
save_video: false
save_model: true
detach_encoder: false
# log
log_interval: 100
# wandb
wandb: false
# MTP
mask_ratio: 0.5
patch_size: 10
block_size: 8
num_attn_layers: 2